XTAIN\FilterQueryBuilder\Configuration\Config:
    xml_root_name: config
    properties:
        value:
            exclude: true
    handler_callbacks:
        serialization:
            xml: serializeToXml
            json: serializeToJson
        deserialization:
            xml: deserializeFromXml
            json: deserializeFromJson
