XTAIN\FilterQueryBuilder\Configuration\Filter:
    xml_root_name: filter
    properties:
        id:
            type: string
            xml_attribute: true
        label:
            type: string
        type:
            type: string
        input:
            type: string
        placeholder:
            type: string
        values:
            type: array<string, string>
            xml_map:
                inline: false
                key_attribute_name: key
                entry_name: entry
        operators:
            type: array<string>
            xml_list:
                inline: false
                entry_name: entry
        validation:
            type: array<string, string>
            xml_map:
                inline: false
                key_attribute_name: key
                entry_name: entry
        config:
            type: XTAIN\FilterQueryBuilder\Configuration\Config
            inline: true
        order:
            type: string
        orderValues:
            exclude: true
